import Head from "next/head";
import Image from "next/image";
import BannerSwatch from "../components/BannerSwatch";
import Header from "../components/Header";
import HeroBanner from "../components/HeroBanner";
import MegaMenu from "../components/MegaMenu";
// import styles from "../styles/Home.module.css";
import styled from "styled-components";

const IndexWrapper = styled.div`
  header {
    margin-bottom: 30px;
  }
  /*  */
`;

export default function Home() {
  // Image Swatch Change, Datas
  const Data1 = {
    heading: <>FrameWorks </>,
    // description: (
    //   <>
    //     <ul>
    //       <li>ReactJS</li>
    //       <li>NextJS</li>
    //       <li>WordPress</li>
    //     </ul>
    //   </>
    // ),
    types: [
      {
        swatch_color: "/assets/bannerSwatch/reactjs-icon.png",
        image_url: "/assets/bannerSwatch/reactjs.jpg",
        // mobile_image_url: "/assets/mobile/shaker-bar-cabinets-grey.jpg",
      },
      {
        swatch_color: "/assets/bannerSwatch/nextjs-icon-2.png",
        image_url: "/assets/bannerSwatch/nextjs.jpg",
        // mobile_image_url: "/assets/mobile/shaker-bar-cabinets-grey.jpg",
      },
      {
        swatch_color: "/assets/bannerSwatch/wp-icon.png",
        image_url: "/assets/bannerSwatch/wp-banner.png",
        // mobile_image_url: "/assets/mobile/shaker-bar-cabinets-white.jpg",
      },
    ],
  };
  return (
    <IndexWrapper className="">
      <Head>
        <title>WorkBase!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MegaMenu />
      <Header />
      <HeroBanner />

      {/*  */}
      <section className="bannerSwatch section-top-padding">
        <BannerSwatch {...Data1} flex_direction="column" />
      </section>
      {/*  */}
    </IndexWrapper>
  );
}
